In [3]:
import pandas as pd  #Load and analyze data
import matplotlib.pyplot as plt #Create charts
import seaborn as sns #Professional statistical visualizations

In [4]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\lenovo\anaconda3\lib\site-packages (9.7.0)

In [5]:
import mysql.connector

print("MySQL Connector Installed Successfully!")

MySQL Connector Installed Successfully!

In [6]:
import sys
print(sys.executable)

C:\Users\LENOVO\anaconda3\python.exe

In [7]:
!pip --version

pip 25.3 from C:\Users\LENOVO\anaconda3\Lib\site-packages\pip (python 3.13)

In [8]:
import pandas as pd
import mysql.connector

In [9]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Tanu2026",
    database="restaurant_db"
)

In [10]:
query = "SHOW COLUMNS FROM order_details;"
pd.read_sql(query, connection)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6604\990500758.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connection)

              Field      Type Null  Key Default Extra
0  order_details_id  smallint   NO  PRI    None
1          order_id  smallint   NO         None
2        order_date      date  YES         None
3        order_time      time  YES         None
4           item_id  smallint  YES         None

In [11]:
query = "SHOW COLUMNS FROM menu_items;"
pd.read_sql(query, connection)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6604\2214210483.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, connection)

          Field          Type Null  Key Default Extra
0  menu_item_id      smallint   NO  PRI    None
1     item_name   varchar(45)  YES         None
2      category   varchar(45)  YES         None
3         price  decimal(5,2)  YES         None

In [12]:
query = """
SELECT
    od.order_id,
    od.order_date,
    od.order_time,
    mi.menu_item_id,
    mi.item_name,
    mi.category,
    mi.price
FROM order_details od
INNER JOIN menu_items mi
ON od.item_id = mi.menu_item_id;
"""

rdb = pd.read_sql(query, connection)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6604\58105172.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  rdb = pd.read_sql(query, connection)

In [13]:
pd.read_sql("SHOW COLUMNS FROM order_details;", connection)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6604\684254691.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SHOW COLUMNS FROM order_details;", connection)

              Field      Type Null  Key Default Extra
0  order_details_id  smallint   NO  PRI    None
1          order_id  smallint   NO         None
2        order_date      date  YES         None
3        order_time      time  YES         None
4           item_id  smallint  YES         None

In [14]:
rdb.head() ## First 5 records

,order_id,order_date,order_time,menu_item_id,item_name,category,price
0,1,2023-01-01,0 days 11:38:36,109,Korean Beef Bowl,Asian,17.95
1,2,2023-01-01,0 days 11:57:40,108,Tofu Pad Thai,Asian,14.50
2,2,2023-01-01,0 days 11:57:40,124,Spaghetti,Italian,14.50
3,2,2023-01-01,0 days 11:57:40,117,Chicken Burrito,Mexican,12.95
4,2,2023-01-01,0 days 11:57:40,129,Mushroom Ravioli,Italian,15.50

In [15]:
rdb.tail() # Last 5 records

,order_id,order_date,order_time,menu_item_id,item_name,category,price
12092,5369,2023-03-31,0 days 22:05:04,109,Korean Beef Bowl,Asian,17.95
12093,5369,2023-03-31,0 days 22:05:04,129,Mushroom Ravioli,Italian,15.50
12094,5369,2023-03-31,0 days 22:05:04,120,Steak Torta,Mexican,13.95
12095,5369,2023-03-31,0 days 22:05:04,122,Chips & Salsa,Mexican,7.00
12096,5370,2023-03-31,0 days 22:15:48,122,Chips & Salsa,Mexican,7.00

In [16]:
rdb.shape #how many rows and columns

(12097, 7)

In [17]:
rdb.columns #columns names

Index(['order_id', 'order_date', 'order_time', 'menu_item_id', 'item_name',
       'category', 'price'],
      dtype='object')

In [18]:
rdb.dtypes #checking data types

order_id                  int64
order_date               object
order_time      timedelta64[ns]
menu_item_id              int64
item_name                object
category                 object
price                   float64
dtype: object

In [19]:
rdb.info #complete information

<bound method DataFrame.info of        order_id  order_date      order_time  menu_item_id         item_name  \
0             1  2023-01-01 0 days 11:38:36           109  Korean Beef Bowl
1             2  2023-01-01 0 days 11:57:40           108     Tofu Pad Thai
2             2  2023-01-01 0 days 11:57:40           124         Spaghetti
3             2  2023-01-01 0 days 11:57:40           117   Chicken Burrito
4             2  2023-01-01 0 days 11:57:40           129  Mushroom Ravioli
...         ...         ...             ...           ...               ...
12092      5369  2023-03-31 0 days 22:05:04           109  Korean Beef Bowl
12093      5369  2023-03-31 0 days 22:05:04           129  Mushroom Ravioli
12094      5369  2023-03-31 0 days 22:05:04           120       Steak Torta
12095      5369  2023-03-31 0 days 22:05:04           122     Chips & Salsa
12096      5370  2023-03-31 0 days 22:15:48           122     Chips & Salsa

      category  price
0        Asian  17.95
1        Asian  14.50
2      Italian  14.50
3      Mexican  12.95
4      Italian  15.50
...        ...    ...
12092    Asian  17.95
12093  Italian  15.50
12094  Mexican  13.95
12095  Mexican   7.00
12096  Mexican   7.00

[12097 rows x 7 columns]>

In [20]:
rdb.describe() #numerical columns

           order_id                 order_time  menu_item_id         price
count  12097.000000                      12097  12097.000000  12097.000000
mean    2692.569149  0 days 16:22:19.455071505    115.202282     13.161767
std     1545.826452  0 days 03:06:05.874340152      9.387580      3.986392
min        1.000000            0 days 10:50:46    101.000000      5.000000
25%     1353.000000            0 days 13:26:19    107.000000     10.500000
50%     2711.000000            0 days 16:30:20    114.000000     13.950000
75%     4020.000000            0 days 18:52:11    123.000000     16.500000
max     5370.000000            0 days 23:05:24    132.000000     19.950000

In [21]:
#categorical columns

rdb.describe(include='object')

#This gives insights into:

# Number of unique categories
# Most frequent item
# Most frequent category

        order_date  item_name category
count        12097      12097    12097
unique          90         32        4
top     2023-02-01  Hamburger    Asian
freq           186        622     3470

In [22]:
#Check whether the dataset contains any missing (NULL) values

rdb.isnull().sum()

order_id        0
order_date      0
order_time      0
menu_item_id    0
item_name       0
category        0
price           0
dtype: int64

In [23]:
#Check whether the dataset contains duplicate rows.

rdb.duplicated().sum()

np.int64(307)

In [24]:
#Calculate the total revenue in Python and compare it with your SQL result.

rdb['price'].sum()

np.float64(159217.9)

In [25]:

print("Total Revenue:",rdb['price'].sum())

Total Revenue: 159217.9

In [26]:
#Calculate the total number of unique orders in Python.
rdb['order_id'].nunique()

5343

In [27]:
#Calculate total revenue generated by each category.

rdb.groupby("category")["price"].sum().sort_values(ascending=False)

category
Italian     49462.70
Asian       46720.65
Mexican     34796.80
American    28237.75
Name: price, dtype: float64

In [28]:
#Display the Distribution of Menu Item Prices

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df["price"], bins=20)
plt.title("Distribution of Menu Item Prices")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()

NameError: name 'df' is not defined

In [ ]:
#Display the Top 10 Selling Menu Items

top_items = (
    df.groupby("item_name")
      .size()
      .sort_values(ascending=False)
      .head(10)
)

plt.figure(figsize=(10,5))
top_items.plot(kind="bar")
plt.title("Top 10 Selling Menu Items")
plt.xlabel("Menu Item")
plt.ylabel("Number of Orders")
plt.xticks(rotation=45)
plt.show()

In [ ]:
#Display the Bottom 10 Selling Menu Items

bottom_items = (
    df.groupby("item_name")
      .size()
      .sort_values(ascending=True)
      .head(10)
)

plt.figure(figsize=(10,5))
bottom_items.plot(kind="barh")
plt.title("Bottom 10 Selling Menu Items")
plt.xlabel("Number of Orders")
plt.ylabel("Menu Item")
plt.show()

In [ ]:
#Revenue by Category

category_revenue = (
    df.groupby("category")["price"]
      .sum()
      .sort_values(ascending=False)
)

plt.figure(figsize=(8,5))
category_revenue.plot(kind="bar")
plt.title("Revenue by Category")
plt.xlabel("Category")
plt.ylabel("Revenue")
plt.xticks(rotation=0)
plt.show()

In [ ]:
# Revenue Contribution Percentage

revenue_percentage = (
    df.groupby("category")["price"]
      .sum()
)

plt.figure(figsize=(7,7))
revenue_percentage.plot(
    kind="pie",
    autopct="%1.1f%%",
    startangle=90
)
plt.ylabel("")
plt.title("Revenue Contribution by Category")
plt.show()

In [ ]:
#Most Expensive & Least Expensive Menu Items

print("Most Expensive Item:")
print(df.loc[df["price"].idxmax(), ["item_name", "category", "price"]])

print("\nLeast Expensive Item:")
print(df.loc[df["price"].idxmin(), ["item_name", "category", "price"]])

In [ ]:
rdb["item_name"].value_counts().sort_values().head(1)

In [ ]:
average_order_value = (
    rdb.groupby("order_id")["price"]
      .sum()
      .mean()
)

print("Average Order Value: ₹", round(average_order_value, 2))

In [29]:
rdb.to_csv("restaurant_orders_cleaned.csv", index=False)